apiVersion: v1
kind: Secret
metadata:
  name: festival-secrets
  namespace: festival-system
type: Opaque
stringData:
  mssql-sa-password: ChangeThis_StrongPassword123!
  postgres-password: festivalpass
  mysql-root-password: rootpass
  mysql-password: festivalpass
  mongo-password: festivalpass
  mongodb-uri: mongodb://festival:festivalpass@mongodb:27017/paymentdb?authSource=admin
  rabbitmq-password: festivalpass
