apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-secrets.example.yaml
  - 02-data-infrastructure.yaml
  - service-discovery.yaml
  - api-gateway.yaml
  - event-service.yaml
  - ticket-service.yaml
  - user-service.yaml
  - payment-service.yaml
  - notification-service.yaml
